# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: 2010-09-09
Description: EMR Serverless full deployment stack

Parameters:
  EMRServerlessBucket:
    Type: String

Resources:

  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      Code:
        S3:
          Bucket: !Ref EMRServerlessBucket
          Key: source/sbt-sample.zip
      RepositoryName: !Sub ${AWS::StackName}-sbt-sample-repo
  RepositoryOnCommit:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.codecommit
        resources:
          - !GetAtt CodeCommitRepository.Arn
        detail-type:
          - CodeCommit Repository State Change
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceName:
            - main
      State: ENABLED
      Targets:
        - Arn: !GetAtt CodeBuildProject.Arn
          Id: Target0
          RoleArn: !GetAtt ProjectEventsRole.Arn
  ProjectEventsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
        Version: 2012-10-17
  ProjectEventsRoleDefaultPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action: 'codebuild:StartBuild'
            Effect: Allow
            Resource: !GetAtt CodeBuildProject.Arn
        Version: 2012-10-17
      PolicyName: ProjectEventsRoleDefaultPolicy
      Roles:
        - !Ref ProjectEventsRole
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: S3
        Location: !Ref EMRServerlessBucket
        Path: "builds"
        OverrideArtifactName: true
        NamespaceType: NONE
        Packaging: NONE
      Description: "Codebuild for sbt-sample"
      Environment:
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:4.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      Name: !Sub ${AWS::StackName}-sbt-sample-project
      ServiceRole: !GetAtt ProjectRole.Arn
      Source:
        Location: !GetAtt CodeCommitRepository.CloneUrlHttp
        Type: CODECOMMIT
      SourceVersion: refs/heads/main

  ProjectRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: 2012-10-17
    Metadata:
      'aws:cdk:path': CodePipeline/Project/Role/Resource
  ProjectRoleDefaultPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action: 'codecommit:GitPull'
            Effect: Allow
            Resource: !GetAtt CodeCommitRepository.Arn
          - Action:
              - 's3:Abort*'
              - 's3:DeleteObject*'
              - 's3:GetBucket*'
              - 's3:GetObject*'
              - 's3:List*'
              - 's3:PutObject'
              - 's3:PutObjectLegalHold'
              - 's3:PutObjectRetention'
              - 's3:PutObjectTagging'
              - 's3:PutObjectVersionTagging'
            Effect: Allow
            Resource:
              - !Sub "arn:aws:s3:::${EMRServerlessBucket}/*"
          - Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:'
                  - !Ref 'AWS::Partition'
                  - ':logs:'
                  - !Ref 'AWS::Region'
                  - ':'
                  - !Ref 'AWS::AccountId'
                  - ':log-group:/aws/codebuild/'
                  - !Ref CodeBuildProject
                  - ':*'
              - !Join
                - ''
                - - 'arn:'
                  - !Ref 'AWS::Partition'
                  - ':logs:'
                  - !Ref 'AWS::Region'
                  - ':'
                  - !Ref 'AWS::AccountId'
                  - ':log-group:/aws/codebuild/'
                  - !Ref CodeBuildProject
          - Action:
              - 'codebuild:BatchPutCodeCoverages'
              - 'codebuild:BatchPutTestCases'
              - 'codebuild:CreateReport'
              - 'codebuild:CreateReportGroup'
              - 'codebuild:UpdateReport'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:'
                - !Ref 'AWS::Partition'
                - ':codebuild:'
                - !Ref 'AWS::Region'
                - ':'
                - !Ref 'AWS::AccountId'
                - ':report-group/'
                - !Ref CodeBuildProject
                - '-*'
        Version: 2012-10-17
      PolicyName: ProjectRoleDefaultPolicy
      Roles:
        - !Ref ProjectRole

